{% set name = "mkdocstrings-python" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings-python-{{ version }}.tar.gz
  sha256: c64fbada8bc5b720a3fed89fcc73f2edced16fa68e106156e780c0e4aec5f8bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - pdm
  run:
    - python >=3.7
    - mkdocstrings >=0.18
    - griffe >=0.11.1

test:
  commands:
    - pip check
    - pytest tests.py
  requires:
    - pip
    - pytest
  files:
    - tests.py

about:
  home: https://pypi.org/project/mkdocstrings-python/
  doc_url: https://mkdocstrings.github.io/python
  dev_url: https://github.com/mkdocstrings/python
  summary: A Python handler for mkdocstrings.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
