{% set name = "mkdocstrings-python" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings-python-{{ version }}.tar.gz
  sha256: 45a8107dfc037c1c55013afb439eaaf59e8076920cfaa61d51c45db2b96e86d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - pdm
  run:
    - python >=3.7
    - mkdocstrings >=0.19
    - griffe >=0.24

test:
  imports:
    - mkdocstrings_handlers.python
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mkdocstrings-python/
  doc_url: https://mkdocstrings.github.io/python
  dev_url: https://github.com/mkdocstrings/python
  summary: A Python handler for mkdocstrings.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
